/**
 * HUMATRIX DEVELOPMENT CORE
 * =========================
 * Typisierter Auszug aus dem Humatrix Science Knowledge Core v2
 * (25 Knowledge-Module + 34 evidenzbasierte Interventionen).
 *
 * Diese Datei ist der METHODIK-KERN der App: Sie verbindet das
 * diagnostische Profil eines Trainers mit konkreten, wissenschaftlich
 * anschlussfähigen Entwicklungs-Bausteinen.
 *
 * GENERIERT aus knowledge/humatrix_*_v2.json — NICHT manuell editieren.
 * Stand: 2026-05-29 · 74 Quellen · Evidenzgrade A / A- / B+ / B.
 *
 * GOVERNANCE (Leitplanken aus M01):
 * - Keine klinische Diagnostik. Nur Entwicklungs- & Coachinghinweise.
 * - Humatrix-Typen sind Coaching-Hypothesen, keine Persönlichkeitsschubladen.
 * - Interne Methodik & Rohquellen NIE im externen Report zeigen.
 */

export type EvidenceGrade = 'A' | 'A-' | 'B+' | 'B';
export type Audience = string;

export type KnowledgeModule = {
  id: string;
  name: string;
  category: string;
  constructs: string[];
  appTargets: string[];
  /** Was im Report über dieses Konstrukt gesagt werden DARF. */
  allowed: string;
  /** Was NIE behauptet werden darf (Claim-Grenze). */
  forbidden: string;
};

export type Intervention = {
  id: string;
  moduleId: string;
  name: string;
  audience: Audience;
  useCase: string;
  durationMin: number | null;
  steps: string[];
  contraindication: string;
  evidence: EvidenceGrade;
};

export const KNOWLEDGE_MODULES: KnowledgeModule[] = [
  {
    id: 'M01_governance_ethics_claim_safety',
    name: 'Governance, Ethik & Claim-Sicherheit',
    category: 'Governance',
    constructs: ['symptoms vs diagnosis', 'voluntary participation', 'role-based visibility', 'data minimization', 'duty of care'],
    appTargets: ['Consent', 'Release Gate', 'External Delivery Layer', 'Report Wording', 'Red Flag Routing'],
    allowed: 'Entwicklungs- und Coachinghinweise im heutigen Kontext.',
    forbidden: 'Diagnose, klinischer Zustand, objektiver Mental-Health-Test.',
  },
  {
    id: 'M02_self_determination_motivation',
    name: 'Selbstmotivation & psychologische Grundbedürfnisse',
    category: 'Motivation',
    constructs: ['autonomy', 'competence', 'relatedness', 'autonomous motivation', 'controlled motivation'],
    appTargets: ['Coach Leadership Scan', 'Player Letter', 'Club Values Fit', '14-Tage-Aufgabe'],
    allowed: 'Der Spieler wirkt stärker, wenn Ziel, Rolle und Handlungsspielraum klar verbunden sind.',
    forbidden: 'Mehr Druck erzeugt automatisch mehr Motivation.',
  },
  {
    id: 'M03_goal_setting_action_tracking',
    name: 'Zielsetzung, Mikroziele & Action Tracking',
    category: 'Performance Psychology',
    constructs: ['process goals', 'implementation intentions', 'review cycles', 'success metrics'],
    appTargets: ['Reset Plan', 'Action Tracking', 'Season Dashboard', 'Coach Briefing'],
    allowed: 'Für die nächsten 14 Tage wird ein beobachtbares Verhalten trainiert.',
    forbidden: 'Der Spieler muss nur mental stärker werden.',
  },
  {
    id: 'M04_coach_athlete_relationship',
    name: 'Coach-Spieler-Beziehung & Arbeitsbündnis',
    category: 'Coach',
    constructs: ['closeness', 'commitment', 'complementarity', 'trust', 'working alliance'],
    appTargets: ['Coach-Team-Fit', 'Coach-Fremdbild', 'Player Need', 'Coach Briefing'],
    allowed: 'Die Coach-Spieler-Passung braucht klare Rollenkommunikation und Beziehungspflege.',
    forbidden: 'Der Coach passt nicht zu diesem Spieler.',
  },
  {
    id: 'M05_coach_leadership_style',
    name: 'Trainerführung & Führungsstil',
    category: 'Coach',
    constructs: ['directiveness', 'structure', 'autonomy support', 'relationship orientation', 'pressure communication', 'bank player management'],
    appTargets: ['Coach Leadership Scan', 'Manager Brief', 'Coach Reflection Pulse'],
    allowed: 'Premium-Führung bedeutet nicht weich, sondern passend, klar und kontextsensibel.',
    forbidden: 'Ein Führungsstil ist immer richtig.',
  },
  {
    id: 'M06_feedback_communication_error_culture',
    name: 'Feedback, Kommunikation & Fehlerkultur',
    category: 'Coach/Team',
    constructs: ['feedback quality', 'error culture', 'voice', 'psychological safety', 'conflict safety'],
    appTargets: ['Club Values Fit', 'Coach Scan', 'Team Cohesion', 'Player Letter'],
    allowed: 'Das Team braucht mehr harte Klarheit ohne Bloßstellung.',
    forbidden: 'Spieler dürfen keine Kritik bekommen.',
  },
  {
    id: 'M07_team_cohesion',
    name: 'Teamkohäsion: Task/Social, Rollen, Zugehörigkeit',
    category: 'Team',
    constructs: ['task cohesion', 'social cohesion', 'role clarity', 'belonging', 'bank culture'],
    appTargets: ['Team Cohesion Scan', 'Manager KPI', 'Season Trend'],
    allowed: 'Die Teamkohäsion wirkt stabil/beobachtungswürdig/kritisch in spezifischen Teilbereichen.',
    forbidden: 'Die Mannschaft hält zusammen, also gewinnt sie.',
  },
  {
    id: 'M08_team_network_direct',
    name: 'Team Network Direct & sensible Netzwerkanalyse',
    category: 'Team Intelligence',
    constructs: ['positive nominations', 'critical nominations', 'bridges', 'subgroups', 'isolation', 'leadership centrality'],
    appTargets: ['Team Network', 'Leadership Coverage', 'Integration Risk', 'Consultant Report'],
    allowed: 'Es gibt Hinweise auf Spannungen zwischen Rollengruppen.',
    forbidden: 'Spieler A wurde von Spieler B negativ genannt.',
  },
  {
    id: 'M09_athlete_leadership',
    name: 'Athlete Leadership & Leadership Coverage',
    category: 'Leadership',
    constructs: ['task leader', 'motivational leader', 'social leader', 'external leader', 'identity leader'],
    appTargets: ['Leadership Coverage', 'Team Matrix', 'Manager Report', 'Leadership Group'],
    allowed: 'Leadership-Abdeckung ist vollständig/lückenhaft in spezifischen Rollen.',
    forbidden: 'Der Kapitän ist automatisch der wichtigste Leader.',
  },
  {
    id: 'M10_team_resilience_pressure_phase',
    name: 'Teamresilienz, Krise & Druckphase',
    category: 'Team Performance',
    constructs: ['collective coping', 'stress adaptation', 'shared resources', 'team confidence', 'communication under stress'],
    appTargets: ['Crisis Pulse', 'Season Risk Watch', 'Pressure Phase Briefing'],
    allowed: 'Die Mannschaft zeigt aktuell Ressourcen/Bruchstellen im Umgang mit Druck.',
    forbidden: 'Das Team ist resilient/nicht resilient als fixe Eigenschaft.',
  },
  {
    id: 'M11_club_dna_culture_alignment',
    name: 'Club-DNA, Kulturfit & Soll-Ist-Abgleich',
    category: 'Club Intelligence',
    constructs: ['values alignment', 'error culture', 'bench culture', 'development culture', 'identity'],
    appTargets: ['Club Values Fit', 'Club Values Scan', 'Manager Report', 'Executive Brief'],
    allowed: 'Zwischen gewünschter und erlebter Kultur besteht ein Gap in X.',
    forbidden: 'Dieser Club hat schlechte Kultur.',
  },
  {
    id: 'M12_roles_status_bench_culture',
    name: 'Rollen, Status, Bankkultur & Kader 12–25',
    category: 'Team/Manager',
    constructs: ['role clarity', 'status threat', 'bench integration', 'fair communication', 'impact readiness'],
    appTargets: ['Bench & Role Pulse', 'Coach Briefing', 'Manager Report', 'Action Plan'],
    allowed: 'Für Kaderplätze 12–25 ist Rollenkommunikation aktuell hoch relevant.',
    forbidden: 'Bankspieler sind problematisch.',
  },
  {
    id: 'M13_focus_vigilance_fatigue',
    name: 'Focus & Vigilance: Reaktion, Tagesform, Müdigkeit',
    category: 'Computer Task',
    constructs: ['reaction time', 'vigilance', 'lapses', 'sleep/fatigue context', 'device latency'],
    appTargets: ['Focus & Impulse Test', 'Day Form', 'Quality Flags'],
    allowed: 'Hinweis auf Konzentrationsstabilität im heutigen standardisierten Clubsetting.',
    forbidden: 'Objektiver Laborwert oder klinische Aufmerksamkeit.',
  },
  {
    id: 'M14_impulse_inhibitory_control',
    name: 'Impulskontrolle & Entscheidungshemmung',
    category: 'Computer Task',
    constructs: ['inhibitory control', 'false alarms', 'missed trials', 'go/no-go accuracy', 'conflict reaction'],
    appTargets: ['Focus & Impulse Test', 'Pressure Reset', 'Player Letter'],
    allowed: 'Hinweis auf Impulsstabilität unter heutiger Aufgabenbedingung.',
    forbidden: 'Der Spieler hat ein Impulskontrollproblem.',
  },
  {
    id: 'M15_pressure_emotion_reset',
    name: 'Druck, Fehlerreaktion & Emotion Reset',
    category: 'Pressure/Reset',
    constructs: ['pressure drop', 'post-error accuracy', 'reset speed', 'emotion tagging', 'coping selection'],
    appTargets: ['Digital Pressure Test', 'Player Letter', 'Coach Briefing'],
    allowed: 'Der Spieler profitiert unter Fehlerdruck von kurzer Reset-Routine X.',
    forbidden: 'Der Spieler ist nicht druckresistent.',
  },
  {
    id: 'M16_workload_tlx_rpe_context',
    name: 'Workload, NASA-TLX/RPE & subjektive Belastung',
    category: 'Workload',
    constructs: ['mental demand', 'time pressure', 'effort', 'frustration', 'RPE', 'subjective workload'],
    appTargets: ['NASA-TLX/RPE', 'Pulse', 'Season Dashboard'],
    allowed: 'Die subjektive Belastung nach dem Test war erhöht.',
    forbidden: 'Objektiver physiologischer Belastungswert.',
  },
  {
    id: 'M17_sleep_recovery_readiness',
    name: 'Schlaf, Recovery & Readiness-Kontext',
    category: 'Recovery',
    constructs: ['sleep quality', 'fatigue', 'recovery', 'competition sleep', 'readiness'],
    appTargets: ['Day Form', 'Always-On Pulse', 'Matchweek Pulse'],
    allowed: 'Aufgrund niedriger Schlafqualität sind Reaktionswerte vorsichtig zu interpretieren.',
    forbidden: 'Der Spieler schläft klinisch schlecht.',
  },
  {
    id: 'M18_burnout_overload_risk',
    name: 'Burnout-, Übersteuerungs- & Belastungsrisiko',
    category: 'Wellbeing',
    constructs: ['exhaustion', 'sport devaluation', 'stress', 'controlled motivation', 'overload'],
    appTargets: ['Pulse', 'Manager Risk Watch', 'Consultant Report'],
    allowed: 'Es gibt Hinweise auf erhöhten Belastungs- und Gesprächsbedarf.',
    forbidden: 'Der Spieler hat Burnout.',
  },
  {
    id: 'M19_perfectionism_high_standards',
    name: 'Perfektionismus, hohe Standards & Selbstkritik',
    category: 'Player Pattern',
    constructs: ['self-oriented perfectionism', 'perfectionistic concerns', 'stress', 'coping', 'burnout risk'],
    appTargets: ['Humatrix Types', 'Player Letter', 'Coach Need'],
    allowed: 'Hohe Standards sind Stärke; unter Bewertungsdruck kann die Qualität enger werden.',
    forbidden: 'Der Spieler ist Perfektionist als Diagnose.',
  },
  {
    id: 'M20_injury_return_to_play_mental',
    name: 'Injury / Return-to-Play Mental Pulse',
    category: 'Injury Add-on',
    constructs: ['body confidence', 'fear of re-injury', 'return confidence', 'patience', 'team connection'],
    appTargets: ['RTP Pulse', 'Coach/Reha Brief', 'Manager Risk Watch'],
    allowed: 'Für die Rückkehr braucht der Spieler klare körperliche und mentale Rückkehrsicherheit.',
    forbidden: 'Der Spieler ist medizinisch bereit/nicht bereit.',
  },
  {
    id: 'M21_dual_career_transition_pressure',
    name: 'Dual Career, Schule/Studium, Vertrag & Übergangsdruck',
    category: 'Transition',
    constructs: ['dual demands', 'identity', 'career transition', 'support network', 'mental health literacy'],
    appTargets: ['Academy Add-on', 'Transition Pulse', 'Player Letter'],
    allowed: 'Der Übergang braucht koordinierte Begleitung zwischen Sport, Ausbildung und Umfeld.',
    forbidden: 'Der Spieler ist mental nicht bereit.',
  },
  {
    id: 'M22_parent_agent_stakeholder_pressure',
    name: 'Eltern, Berater & Umfeld-Druck',
    category: 'Stakeholder',
    constructs: ['parental pressure', 'support climate', 'agent pressure', 'expectations', 'communication boundaries'],
    appTargets: ['Academy/Young Pro Add-on', 'Manager Brief', 'Consultant Notes'],
    allowed: 'Das Umfeld sollte in die Unterstützungslogik klarer eingebunden werden.',
    forbidden: 'Die Eltern/der Berater sind das Problem.',
  },
  {
    id: 'M23_transfer_fit_talent_context',
    name: 'Transfer-Fit, Talententwicklung & Kaderarchitektur',
    category: 'Manager/Transfer',
    constructs: ['psychological team architecture', 'role fit', 'coach fit', 'club-DNA fit', 'talent context'],
    appTargets: ['Transfer Fit Report', 'Manager Brief', 'Team Matrix'],
    allowed: 'Der Kandidat könnte eine aktuell fehlende Teamfunktion ergänzen.',
    forbidden: 'Humatrix entscheidet, ob der Spieler verpflichtet werden soll.',
  },
  {
    id: 'M24_womens_football_specific_context',
    name: 'Frauenfußball-spezifische Kontexte',
    category: 'Women Football',
    constructs: ['female pro football mental health', 'menstrual health literacy', 'privacy', 'support structures'],
    appTargets: ['Women Club Mode', 'Player Consent', 'Wellbeing Add-ons'],
    allowed: 'Optionales, vertrauliches Gesundheits-/Wellbeing-Monitoring kann die Betreuung verbessern.',
    forbidden: 'Zyklusdaten als Leistungslabel oder Selektionsgrund verwenden.',
  },
  {
    id: 'M25_external_info_layer_science_translation',
    name: 'External Info Layer: Wissenschaft verständlich machen',
    category: 'External Delivery',
    constructs: ['science translation', 'data literacy', 'claim boundaries', 'action orientation'],
    appTargets: ['/share/info', 'Manager Info', 'Coach Info', 'Player Info'],
    allowed: 'Diese Auswertung zeigt kuratierte Entwicklungsimpulse.',
    forbidden: 'Methodikdatenbank, Scoringformeln oder Rohdaten extern zeigen.',
  },
  {
    id: 'M26_coach_self_management',
    name: 'Selbstführung, Belastungssteuerung & Erholung des Trainers',
    category: 'Coach Self-Leadership',
    constructs: ['self-regulation', 'recovery management', 'support network', 'boundary setting', 'energy awareness'],
    appTargets: ['Coach Scan', 'Führung unter Druck', '14-Tage-Aufgabe', 'Entwicklungspfad'],
    allowed:
      'Wie der Trainer die eigene Belastung steuert und Erholung schützt, ist Teil seiner Führungsqualität — Entwicklungs- und Coachinghinweis im heutigen Kontext.',
    forbidden: 'Burnout-Diagnose, klinische Erschöpfung oder Therapieempfehlung für den Trainer.',
  },
];

export const INTERVENTIONS: Intervention[] = [
  {
    id: 'I001',
    moduleId: 'M03_goal_setting_action_tracking',
    name: '14-Tage-Mikroziel',
    audience: 'player',
    useCase: 'Nach Big Club Check oder Player Letter',
    durationMin: 14,
    steps: ['1 klares Verhalten wählen', 'Kontext definieren: Training/Spiel/Bank', 'Erfolgskriterium festlegen', 'nach 14 Tagen mit Coach/Mentaltrainer reviewen'],
    contraindication: 'Keine vagen Ziele; nicht bei akuter Krise ohne Fachsupport',
    evidence: 'A',
  },
  {
    id: 'I002',
    moduleId: 'M03_goal_setting_action_tracking',
    name: '90-Tage-Club-Action-Plan',
    audience: 'manager',
    useCase: 'Nach Manager Brief',
    durationMin: 90,
    steps: ['Top-3 Risiken priorisieren', 'Owner je Maßnahme definieren', 'Success Metric festlegen', 'alle 30 Tage Status prüfen', 'Wirksamkeit bewerten'],
    contraindication: 'Nicht mehr als 5 Aktionen gleichzeitig starten',
    evidence: 'A-',
  },
  {
    id: 'I003',
    moduleId: 'M02_self_determination_motivation',
    name: 'Autonomie-im-Rahmen Gespräch',
    audience: 'coach',
    useCase: 'Spieler braucht Handlungsspielraum',
    durationMin: 15,
    steps: ['Standard erklären', '2 Wahloptionen anbieten', 'Spieler wählt Umsetzungsweg', 'Reviewpunkt vereinbaren'],
    contraindication: 'Nicht als Beliebigkeit verstehen',
    evidence: 'A',
  },
  {
    id: 'I004',
    moduleId: 'M04_coach_athlete_relationship',
    name: 'Coach-Spieler-Arbeitsbündnis Check-in',
    audience: 'coach',
    useCase: 'Coach-Fit Risiko',
    durationMin: 20,
    steps: ['Was brauchst du von mir?', 'Was brauche ich von dir?', 'Wo entsteht Missverständnis?', 'Nächste konkrete Vereinbarung'],
    contraindication: 'Nicht als Therapie; bei Red Flags weiterleiten',
    evidence: 'A-',
  },
  {
    id: 'I005',
    moduleId: 'M06_feedback_communication_error_culture',
    name: 'Fehlerkultur-Reset im Training',
    audience: 'coach',
    useCase: 'Angst vor Fehlern / zögerliches Spiel',
    durationMin: 20,
    steps: ['Fehler als Lernsignal benennen', 'Mutaktion positiv markieren', 'kurze Korrektur geben', 'nächste Aktion fordern'],
    contraindication: 'Nicht Fehler schönreden; klar bleiben',
    evidence: 'A-',
  },
  {
    id: 'I006',
    moduleId: 'M08_team_network_direct',
    name: 'Geschütztes Netzwerk-Review',
    audience: 'consultant',
    useCase: 'Spannungen/Subgruppen sichtbar',
    durationMin: 45,
    steps: ['Rohdaten intern prüfen', 'Muster anonymisieren', '2–3 Teamhypothesen bilden', 'Coach nur kuratierte Handlung geben'],
    contraindication: 'Nie Nennungslisten an Coach/Manager',
    evidence: 'A',
  },
  {
    id: 'I007',
    moduleId: 'M09_athlete_leadership',
    name: 'Leadership-Rollenmatrix Workshop',
    audience: 'team',
    useCase: 'Leadership lückenhaft',
    durationMin: 60,
    steps: ['Task/Motivational/Social/External erklären', 'informelle Leader kuratiert identifizieren', 'Rollen vereinbaren', 'Review nach 30 Tagen'],
    contraindication: 'Nicht nur Kapitän überlasten',
    evidence: 'A-',
  },
  {
    id: 'I008',
    moduleId: 'M10_team_resilience_pressure_phase',
    name: 'Crisis Huddle Protokoll',
    audience: 'team',
    useCase: 'Krisenphase/Niederlagenserie',
    durationMin: 30,
    steps: ['Fakten sammeln', 'Kontrollierbares benennen', 'Leader-Rollen aktivieren', '48h-Kommunikationsregel setzen'],
    contraindication: 'Nicht als Schuldzuweisung nutzen',
    evidence: 'A-',
  },
  {
    id: 'I009',
    moduleId: 'M12_roles_status_bench_culture',
    name: 'Bankrollen-Gespräch 7 Tage',
    audience: 'coach',
    useCase: 'Bankfrust/Rollenunklarheit',
    durationMin: 15,
    steps: ['aktuelle Rolle erklären', 'Impact-Szenario definieren', 'Trainingsziel festlegen', 'nächster Reviewtermin'],
    contraindication: 'Nicht erst nach Eskalation durchführen',
    evidence: 'A-',
  },
  {
    id: 'I010',
    moduleId: 'M13_focus_vigilance_fatigue',
    name: 'Focus-Test Quality Review',
    audience: 'consultant',
    useCase: 'low_sleep/fatigue/device warning',
    durationMin: 5,
    steps: ['Quality Flags prüfen', 'Tagesform danebenlegen', 'nicht überinterpretieren', 'bei Bedarf Retest empfehlen'],
    contraindication: 'Kein Einzelwert als Urteil',
    evidence: 'A-',
  },
  {
    id: 'I011',
    moduleId: 'M15_pressure_emotion_reset',
    name: '3-Atemzüge-Nächste-Aktion Reset',
    audience: 'player',
    useCase: 'Fehler/Frust im Spiel',
    durationMin: 2,
    steps: ['1 Ausatmen verlängern', 'Trigger benennen', 'Cue: nächste Aktion', 'körperliches Signal setzen'],
    contraindication: 'Nicht bei Panik/klinischem Zustand als alleinige Hilfe',
    evidence: 'A-',
  },
  {
    id: 'I012',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Post-Error Routine Training',
    audience: 'player/team',
    useCase: 'Fehlerreaktion langsam',
    durationMin: 10,
    steps: ['Fehler provozieren', 'kurzer Cue', 'nächste Aktion sofort ausführen', 'Coach lobt Reset, nicht Fehlerfreiheit'],
    contraindication: 'Nicht beschämen',
    evidence: 'A-',
  },
  {
    id: 'I013',
    moduleId: 'M16_workload_tlx_rpe_context',
    name: 'Workload Reflection nach Druckmodul',
    audience: 'player',
    useCase: 'hohe Frustration/Belastung',
    durationMin: 6,
    steps: ['Mental demand markieren', 'Frustration markieren', 'eine Coping-Strategie wählen', 'Reportnotiz generieren'],
    contraindication: 'Subjektiv, keine Diagnose',
    evidence: 'A-',
  },
  {
    id: 'I014',
    moduleId: 'M17_sleep_recovery_readiness',
    name: 'Sleep-Readiness Kontextregel',
    audience: 'consultant',
    useCase: 'niedrige Schlafqualität',
    durationMin: 3,
    steps: ['Sleep flag setzen', 'RT/PVT vorsichtig interpretieren', 'Recovery-Hinweis in Player Letter', 'bei Persistenz Fachsupport empfehlen'],
    contraindication: 'Keine Schlafmedizin ersetzen',
    evidence: 'A-',
  },
  {
    id: 'I015',
    moduleId: 'M18_burnout_overload_risk',
    name: 'Overload-Schutzgespräch',
    audience: 'consultant/mentaltrainer',
    useCase: 'Stress+Fatigue Trend hoch',
    durationMin: 25,
    steps: ['Daten trendbasiert prüfen', 'Spielergespräch anbieten', 'Belastungsquellen trennen', 'Staff nur kuratierte Empfehlung geben'],
    contraindication: 'Red Flags nicht an Coach roh geben',
    evidence: 'A-',
  },
  {
    id: 'I016',
    moduleId: 'M19_perfectionism_high_standards',
    name: 'Qualität-vs-Mut Reframing',
    audience: 'player',
    useCase: 'sensibler Perfektionist',
    durationMin: 15,
    steps: ['Stärke benennen', 'Kosten der Bewertungsenge zeigen', 'Mutziel definieren', 'Fehlerabschluss-Routine üben'],
    contraindication: 'Keine Pathologisierung',
    evidence: 'A-',
  },
  {
    id: 'I017',
    moduleId: 'M20_injury_return_to_play_mental',
    name: 'RTP Confidence Ladder',
    audience: 'player/medical',
    useCase: 'Rückkehr nach Verletzung',
    durationMin: 30,
    steps: ['Angstskala erheben', '5 Stufen der Rückkehr definieren', 'Körpervertrauen notieren', 'Medical/Coach Kommunikation abstimmen'],
    contraindication: 'Medizinische Freigabe bleibt extern',
    evidence: 'A-',
  },
  {
    id: 'I018',
    moduleId: 'M21_dual_career_transition_pressure',
    name: 'Transition Map',
    audience: 'player/consultant',
    useCase: 'Schule/Vertrag/Übergang',
    durationMin: 30,
    steps: ['Druckquellen mappen', 'Supportpersonen definieren', '2 Prioritäten wählen', '14-Tage Entlastungsmaßnahme planen'],
    contraindication: 'Nicht mit mangelnder Motivation verwechseln',
    evidence: 'A-',
  },
  {
    id: 'I019',
    moduleId: 'M22_parent_agent_stakeholder_pressure',
    name: 'Stakeholder Boundary Brief',
    audience: 'consultant',
    useCase: 'Umfeld-/Beraterdruck',
    durationMin: 30,
    steps: ['Thema kuratiert erfassen', 'Grenzen definieren', 'Kommunikationskanal klären', 'Player-Schutzregel setzen'],
    contraindication: 'Keine Schuldzuweisung',
    evidence: 'B+',
  },
  {
    id: 'I020',
    moduleId: 'M23_transfer_fit_talent_context',
    name: 'Transfer Mental Function Brief',
    audience: 'manager',
    useCase: 'Kaderplanung',
    durationMin: 25,
    steps: ['fehlende Teamfunktion identifizieren', 'Coach-Fit bewerten', 'Club-DNA Fit prüfen', 'Integrationsrisiko notieren'],
    contraindication: 'Nie alleinige Transferentscheidung',
    evidence: 'A-',
  },
  {
    id: 'I021',
    moduleId: 'M24_womens_football_specific_context',
    name: 'Optional Women’s Wellbeing Consent',
    audience: 'player/practitioner',
    useCase: 'Frauenfußball Zusatzmodul',
    durationMin: 5,
    steps: ['Freiwilligkeit erklären', 'Datensensitivität erklären', 'Auswertungskreis wählen', 'Skip jederzeit ermöglichen'],
    contraindication: 'Keine Pflichtdaten; keine Selektionsnutzung',
    evidence: 'A-',
  },
  {
    id: 'I022',
    moduleId: 'M25_external_info_layer_science_translation',
    name: 'External Info Link nach Report',
    audience: 'manager/coach/player',
    useCase: 'Kunde versteht Auswertung',
    durationMin: 10,
    steps: ['Zielgruppe wählen', 'Info-Modul freigeben', 'Claim-Grenzen anzeigen', 'Nächste Schritte verlinken'],
    contraindication: 'Keine interne Methodik freigeben',
    evidence: 'B+',
  },
  {
    id: 'I023',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Statusverlust-Plan',
    audience: 'player/coach',
    useCase: 'Bankrolle/Statusdruck',
    durationMin: 14,
    steps: ['Klare Rolle + 1 messbare Impact-Aufgabe + ehrliches direktes Gespräch', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I024',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Regeneration-ist-Leistung Plan',
    audience: 'player/coach',
    useCase: 'Überlastung',
    durationMin: 14,
    steps: ['Belastungsgrenzen + Pausen-Erlaubnis + Staff-Abgleich', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I025',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Fehlerabschluss-Routine',
    audience: 'player/coach',
    useCase: 'Fehler/öffentliche Bewertung',
    durationMin: 14,
    steps: ['Fehler benennen + Lernpunkt + nächste mutige Aktion', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I026',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Grenzen-für-Teamverantwortung',
    audience: 'player/coach',
    useCase: 'Überverantwortung',
    durationMin: 14,
    steps: ['Soziale Rolle definieren + eigene Leistung nicht verlieren', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I027',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Freiheitszone-mit-Prinzipien',
    audience: 'player/coach',
    useCase: 'Mikromanagement-Frust',
    durationMin: 14,
    steps: ['Prinzipienrahmen + klare Freiheitszone + defensive Minimalstandards', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I028',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Flexibilitätsfenster',
    audience: 'player/coach',
    useCase: 'Chaos/Rollenwechsel',
    durationMin: 14,
    steps: ['eine kontrollierte variable Aufgabe + kurze Review', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I029',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Sichtbarkeit-in-kleinen-Schritten',
    audience: 'player/coach',
    useCase: 'zu wenig Präsenz',
    durationMin: 14,
    steps: ['1 sichtbare Aktion pro Training + positives Feedback', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I030',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Verbindung-ohne-Vereinnahmung',
    audience: 'player/coach',
    useCase: 'Teamdistanz/Feedbackabwehr',
    durationMin: 14,
    steps: ['respektvolle Direktheit + Teamauftrag + Beziehung über Kompetenz', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I031',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Mutziel-mit-Absicherung',
    audience: 'player/coach',
    useCase: 'Risikovermeidung',
    durationMin: 14,
    steps: ['1 mutige Aktion + Fehlerfreigabe + Absicherung', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I032',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Emotion-zu-Handlung Reset',
    audience: 'player/coach',
    useCase: 'Frust/Provokation',
    durationMin: 14,
    steps: ['Emotionscue + Atem + nächste Aktion + Kartenrisiko-Regel', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I033',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Orientierungsanker',
    audience: 'player/coach',
    useCase: 'Rollenunklarheit',
    durationMin: 14,
    steps: ['1 Mentor + 1 Rollenpriorität + 14-Tage-Standard', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  {
    id: 'I034',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Gegenwart-stabil-halten',
    audience: 'player/coach',
    useCase: 'Vertrag/Zukunftsdruck',
    durationMin: 14,
    steps: ['Zukunftsthema parken + Wochenfokus + Supportperson', 'konkretes Verhalten vereinbaren', 'nach 14 Tagen prüfen'],
    contraindication: 'Typ ist Coaching-Hypothese, keine Persönlichkeitsschublade',
    evidence: 'B+',
  },
  // ---------------------------------------------------------------------------
  // COACH-SELBST-BAUSTEINE (v3_26): direkt an den Trainer adressierte
  // Hilfestellungen für eigene Belastung, Außendruck und schwierige
  // Kommunikation. Schließt die Lücke, dass die bestehenden Druck-/Overload-/
  // Stakeholder-Bausteine auf Spieler bzw. Consultant zugeschnitten waren.
  // Claim-sicher: Entwicklungs-/Coachinghinweise, keine klinische Einordnung.
  // ---------------------------------------------------------------------------
  {
    id: 'I035',
    moduleId: 'M26_coach_self_management',
    name: 'Eigene Belastungssteuerung (Trainer)',
    audience: 'coach',
    useCase: 'Niedrige Selbstregulation/Druckreife — eigene Belastung im Blick behalten',
    durationMin: 20,
    steps: [
      'eigene Belastungsquellen auflisten (sportlich / organisatorisch / zwischenmenschlich)',
      '2 schützbare Erholungsfenster pro Woche fixieren',
      '1–2 Personen benennen, mit denen du Belastung offen besprichst',
      'nach 14 Tagen prüfen: Was hat spürbar entlastet?',
    ],
    contraindication: 'Kein Ersatz für fachliche Unterstützung bei anhaltender Erschöpfung',
    evidence: 'B+',
  },
  {
    id: 'I036',
    moduleId: 'M22_parent_agent_stakeholder_pressure',
    name: 'Außendruck-Grenze setzen (Verein/Eltern/Umfeld)',
    audience: 'coach',
    useCase: 'Druck von außen vermischt sich mit der sportlichen Linie',
    durationMin: 20,
    steps: [
      'sportlichen Kern vom Außendruck trennen (Was ist Sache, was ist Stimmung?)',
      'klären: Was entscheidest du selbst, was kommunizierst du nach außen',
      'eine ruhige, klare Grenzbotschaft formulieren',
      'Kanal und festen Ansprechpartner für das Umfeld festlegen',
    ],
    contraindication: 'Keine Schuldzuweisung an das Umfeld; Grenze sachlich halten',
    evidence: 'B+',
  },
  {
    id: 'I037',
    moduleId: 'M06_feedback_communication_error_culture',
    name: 'Niederlagen-Ansprache strukturieren',
    audience: 'coach',
    useCase: 'Nach Niederlage die Balance zwischen Klartext und Aufbau finden',
    durationMin: 15,
    steps: [
      'kurz die Fakten benennen, ohne Schuldzuweisung',
      'ein kontrollierbares Thema für die nächste Woche wählen',
      'den Blick nach vorn richten (nächste Aufgabe konkret)',
      'einzelne Spieler gezielt stabilisieren statt Kollektivkritik',
    ],
    contraindication: 'Nicht beschönigen und nicht persönlich werden',
    evidence: 'A-',
  },
  {
    id: 'I038',
    moduleId: 'M12_roles_status_bench_culture',
    name: 'Faire Bank-/Rollenbotschaft kommunizieren',
    audience: 'coach',
    useCase: 'Verdienten Spieler auf die Bank setzen / Rolle verändern',
    durationMin: 15,
    steps: [
      'Entscheidung mit klarer, nachvollziehbarer Begründung erklären',
      'den Weg zurück bzw. ein Impact-Szenario aufzeigen',
      'Wertschätzung für die bisherige Leistung sichtbar machen',
      'einen konkreten Reviewtermin vereinbaren',
    ],
    contraindication: 'Nicht erst nach Eskalation; nicht vor der Gruppe bloßstellen',
    evidence: 'A-',
  },
  {
    id: 'I039',
    moduleId: 'M15_pressure_emotion_reset',
    name: 'Persönliche Druck-Vorroutine (Seitenlinie)',
    audience: 'coach',
    useCase: 'Vor entscheidenden Spielen/Momenten in die eigene Grundlinie kommen',
    durationMin: 10,
    steps: [
      'einen persönlichen Anker wählen (kurzer Satz oder Geste)',
      'vor Anpfiff ein längeres Ausatmen + bewussten Fokus setzen',
      'die erste eigene Handlung bei Druck vorab definieren',
      'nach dem Spiel kurz prüfen: hat die Routine getragen?',
    ],
    contraindication: 'Kein Ersatz für die inhaltliche Spielvorbereitung',
    evidence: 'B+',
  },
  {
    id: 'I040',
    moduleId: 'M06_feedback_communication_error_culture',
    name: 'Wirkungs-Check für wichtige Botschaften',
    audience: 'coach',
    useCase: 'Botschaften kommen im Team unterschiedlich an',
    durationMin: 10,
    steps: [
      'nach einer wichtigen Botschaft aktiv nachfragen, wie sie verstanden wurde',
      'den Unterschied zwischen Absicht und Wirkung benennen',
      'gezielt dort nachschärfen, wo es nötig ist',
      'die Rückmeldeschleife sichtbar schließen',
    ],
    contraindication: 'Nicht jede Aussage zerreden; bewusst bei Kernbotschaften einsetzen',
    evidence: 'A-',
  },
];

export const KNOWLEDGE_MODULE_BY_ID: Record<string, KnowledgeModule> =
  Object.fromEntries(KNOWLEDGE_MODULES.map((m) => [m.id, m]));
