import { NextResponse, type NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { requireActiveAssessmentEntitlement } from '@/lib/auth/assessment-entitlement';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function POST(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });

  let body: any;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid request body" }, { status: 400 });
  }
  const { assessment_id, email, invitation_type } = body;

  if (!assessment_id || !email) {
    return NextResponse.json({ error: 'assessment_id und email erforderlich' }, { status: 400 });
  }

  // Diese Route erzeugt AUSSCHLIESSLICH Fremdbild-Einladungen. Spieler-Einladungen
  // (anonymer TeamCheck, ohne E-Mail) laufen separat über die Bulk-Token-Route.
  if (invitation_type !== undefined && invitation_type !== 'fremdbild') {
    return NextResponse.json(
      { error: 'Über diese Route sind nur Fremdbild-Einladungen möglich.' },
      { status: 400 },
    );
  }

  // ZENTRALE Berechtigung (P0): Ownership + aktiviert + bezahlt + bestätigt +
  // NICHT erstattet. Ersetzt die frühere reine Ownership-/Status-Prüfung. Nach
  // einem Refund (purchase.status='refunded') schlägt dies fehl → keine neuen
  // Fremdbild-Einladungen mehr.
  const admin = createAdminClient();
  const ent = await requireActiveAssessmentEntitlement(admin, assessment_id, {
    ownerUserId: user.id,
  });
  if (!ent.ok) return NextResponse.json({ error: ent.error }, { status: ent.status });

  // Fremdbild erst ab Tier 3.
  if (ent.tier < 3) {
    return NextResponse.json({
      error: 'Fremdbild-Einladungen sind erst ab dem 360° Spiegel verfügbar (ab 199 €).'
    }, { status: 403 });
  }

  // Insert invitation (token will be auto-generated by trigger). invitation_type
  // wird hier FEST auf 'fremdbild' gesetzt.
  const { data: invitation, error } = await admin
    .from('invitations')
    .insert({
      parent_assessment_id: assessment_id,
      invited_email: email,
      invitation_type: 'fremdbild',
      status: 'pending',
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true, invitation });
}
