import { NextResponse, type NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function POST(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });

  const body = await request.json();
  const { assessment_id, email, invitation_type } = body;

  if (!assessment_id || !email) {
    return NextResponse.json({ error: 'assessment_id und email erforderlich' }, { status: 400 });
  }

  // Validate ownership
  const { data: assessment } = await supabase
    .from('assessments')
    .select('id, user_id, product:products(tier)')
    .eq('id', assessment_id)
    .eq('user_id', user.id)
    .single();

  if (!assessment) {
    return NextResponse.json({ error: 'Assessment nicht gefunden' }, { status: 404 });
  }

  // Only tier 3+ can use 360°
  const tier = (assessment.product as any)?.tier ?? 0;
  if (invitation_type === 'fremdbild' && tier < 3) {
    return NextResponse.json({
      error: 'Fremdbild-Einladungen sind erst ab dem 360° Spiegel verfügbar (ab 99 €).'
    }, { status: 403 });
  }

  // Insert invitation (token will be auto-generated by trigger)
  const { data: invitation, error } = await supabase
    .from('invitations')
    .insert({
      parent_assessment_id: assessment_id,
      invited_email: email,
      invitation_type: invitation_type ?? 'fremdbild',
      status: 'pending',
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true, invitation });
}
