import { NextResponse, type NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function POST(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });

  let body: any;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid request body" }, { status: 400 });
  }
  const { assessment_id, email, invitation_type } = body;

  if (!assessment_id || !email) {
    return NextResponse.json({ error: 'assessment_id und email erforderlich' }, { status: 400 });
  }

  // Diese Route erzeugt AUSSCHLIESSLICH Fremdbild-Einladungen. Spieler-Einladungen
  // (anonymer TeamCheck, ohne E-Mail) laufen separat über die Bulk-Token-Route.
  if (invitation_type !== undefined && invitation_type !== 'fremdbild') {
    return NextResponse.json(
      { error: 'Über diese Route sind nur Fremdbild-Einladungen möglich.' },
      { status: 400 },
    );
  }

  // Validate ownership
  const { data: assessment } = await supabase
    .from('assessments')
    .select('id, user_id, status, product:products(tier)')
    .eq('id', assessment_id)
    .eq('user_id', user.id)
    .single();

  if (!assessment) {
    return NextResponse.json({ error: 'Assessment nicht gefunden' }, { status: 404 });
  }

  // Fremdbild erst ab Tier 3 — Prüfung jetzt UNBEDINGT (nicht mehr nur, wenn der
  // Typ mitgeschickt wurde).
  const tier = (assessment.product as any)?.tier ?? 0;
  if (tier < 3) {
    return NextResponse.json({
      error: 'Fremdbild-Einladungen sind erst ab dem 360° Spiegel verfügbar (ab 199 €).'
    }, { status: 403 });
  }

  // Nur für freigeschaltete (bezahlte) Assessments.
  if (!['pending', 'in_progress', 'completed', 'report_ready'].includes(assessment.status)) {
    return NextResponse.json({ error: 'assessment not activated' }, { status: 409 });
  }

  // Insert invitation (token will be auto-generated by trigger). invitation_type
  // wird hier FEST auf 'fremdbild' gesetzt.
  const admin = createAdminClient();
  const { data: invitation, error } = await admin
    .from('invitations')
    .insert({
      parent_assessment_id: assessment_id,
      invited_email: email,
      invitation_type: 'fremdbild',
      status: 'pending',
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true, invitation });
}
